### PR TITLE
Make compatible with VSCODE and add default cert.c

### PR DESCRIPTION
**Pull request by peardox**
Ran mkcert.sh as per #4 to create a default certificate the user may override at their option (needs to update README.md at some point I guess)

Made a minor change to u2f.c changing the function definition for tud_hid_report_complete_cb to match that in sdk (as this upsets VSCode)

Note that I can now build fidelio on Windows using VSCode Extension - this will eventually make fidelio far more accessible to others. I've got some more to do on the vscode version but will branch when happier with it.

This should allow me to easily debug my test key in real time on Windows (but it's late so that fun's for the morning)

### CODE REVIEW

**Comment by danielinux** [comment]
Hi, thanks for the PR.

Code changes are OK, and if you can separate from the binary pre-signed cert, I would certainly merge in.

I don't like the idea of providing a binary certificate that is pre-signed with an unknown key by default. It limits the possibility for the user to sign their own devices with a key that is generated ad-hoc and they trust.

 I would be OK with a cmake option like "-DDEMO_CERT" to activate the example certificate, but we would have to find a way to distribute the intermediate files used to sign it, and it would make sense to distribute example cert & private key as PEM for transparency.

**Comment by peardox** [comment]
I've removed cert.c again for now. Somehow or another it would be beneficial to have the makefile create cert.c if not present. Windows + VSCode extension is the problem here though as it doesn't come with openssl as standard. I guess I could ask the maintainer to add it as it'd be a generally useful thing in that toolchain

**Review by danielinux — CHANGES_REQUESTED** [review]
can you also please `git rm -f cert.c`

**Comment by peardox** [comment]
Done

**Review by danielinux — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
